language: php
script: phpunit

php:
    - 5.5
    - 5.4

before_script:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository ppa:gearman-developers/ppa
    - sudo apt-get update
    - sudo apt-get install libgearman-dev gearman
    - yes | pecl install gearman
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
