language: php
script: phpunit

php:
    - 5.5
    - 5.4
    - 5.3

before_script:
    - sudo apt-get install gearman
    - yes | pecl install gearman
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
