language: php
script: 
    - sudo netstat -nlpt
    - phpunit

php:
    - 5.5
    - 5.4
    - 5.6

before_script:
    - sudo apt-get install libgearman-dev gearman
    - yes | pecl install gearman-1.0.3
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install
