<?php
/**
 *  Autoloader function generated by crodas/Autoloader
 *
 *  https://github.com/crodas/Autoloader
 *
 *  This is a generated file, do not modify it.
 */

spl_autoload_register(function ($class) {
    /*
        This array has a map of (class => file)
    */

    // classes {{{
    static $classes = array (
  'crodas\\worker\\engine\\pdo\\cursor' => '/manager.php',
  'crodas\\worker\\engine\\pdo\\stmt' => '/manager.php',
  'crodas\\worker\\engine\\pdo\\connectionmanager' => '/manager.php',
  'crodas\\worker\\engine\\pdo\\task' => '/Task.php',
  'crodas\\worker\\engine\\pdo\\taskentity' => '/generated.php',
  'crodas\\worker\\engine\\pdo\\tasktable' => '/Table/Task.php',
  'crodas\\worker\\engine\\pdo\\tasktableabstract' => '/generated.php',
  'crodas\\worker\\engine\\pdo\\tasktableabstractquerybuilder' => '/generated.php',
);
    // }}}

    // deps {{{
    static $deps    = array (
  'crodas\\worker\\engine\\pdo\\task' => 
  array (
    0 => 
    array (
      0 => 'crodas\\worker\\engine\\pdo\\taskentity',
      1 => 'trait_exists',
    ),
  ),
  'crodas\\worker\\engine\\pdo\\tasktable' => 
  array (
    0 => 
    array (
      0 => 'crodas\\worker\\engine\\pdo\\tasktableabstract',
      1 => 'class_exists',
    ),
  ),
);
    // }}}

    $class = strtolower($class);
    if (isset($classes[$class])) {
        if (!empty($deps[$class])) {
            foreach ($deps[$class] as $zclass) {
                if (is_array($zclass)) {
                    if (!$zclass[1]($zclass[0], false)) {
                        require __DIR__  . $classes[$zclass[0]];
                    }
                } else if (!class_exists($zclass, false)) {
                    require __DIR__  . $classes[$zclass];
                }
            }
        }

        if (is_array($class)) {

            if (!$class[1]($class[0], false)) {

                require __DIR__  . $classes[$class[0]];

            }

        } else if (!class_exists($class, false)) {

            require __DIR__  . $classes[$class];

        }
        return true;
    }

    return false;
});


